services:
  - type: web
    name: legal-doc-ai-backend
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: GEMINI_API_KEY
        sync: false
      - key: QDRANT_API_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true

routes:
  - type: web
    name: api
    domain: legal-doc-ai-api
